environment:
  matrix:
    - RUST: stable
      BITS: 32
      TARGET: pc-windows-gnu
    - RUST: stable
      BITS: 64
      TARGET: pc-windows-gnu

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %RUST% --default-host %ARCH%-%TARGET%
  - SET PATH=C:\Users\appveyor\.cargo\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - rustc -Vv
  - cargo -Vv
  - pacman --noconfirm -S mingw-w64-%ARCH%-gtk3

build_script:
  - mkdir .cargo
  - echo paths = ["."] > .cargo\config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - cargo build
  - cargo build --features gtk_3_18

test: false
