[options]
work_mode = "sys"
library = "Atk"
version = "1.0"
min_cfg_version = "2.4"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
]

ignore = [
	"Atk.BINARY_AGE",
	"Atk.INTERFACE_AGE",
	"Atk.MAJOR_VERSION",
	"Atk.MICRO_VERSION",
	"Atk.MINOR_VERSION",
	"Atk.VERSION_MIN_REQUIRED",
]
