[options]
work_mode = "sys"
library = "GObject"
version = "2.0"
min_cfg_version = "2.32"
external_libraries = [
   "GLib",
]

ignore = [
   "GObject.VaClosureMarshal",
   "GObject.SignalCVaMarshaller",
]

[[object]]
name = "GObject.Object"
status = "generate"
    [[object.function]]
    pattern = "(get|set)v"
    # incorrect GIR due to gobject-introspection GitLab issue #189
    ignore = true
    [[object.function]]
    name = "new_with_properties"
    # incorrect GIR due to gobject-introspection GitLab issue #189
    ignore = true
