[options]
work_mode = "sys"
library = "Gtk"
version = "3.0"
min_cfg_version = "3.4"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Atk",
   "GdkPixbuf",
   "Gdk",
   "Pango",
   "Cairo",
]

manual = [
   "xlib.Window",
]

ignore = [
	"Gtk.BINARY_AGE",
	"Gtk.INTERFACE_AGE",
	"Gtk.MAJOR_VERSION",
	"Gtk.MICRO_VERSION",
	"Gtk.MINOR_VERSION",
]


[[object]]
name = "Gtk.IconTheme"
status = "generate"
    [[object.function]]
    pattern = "(get|set)_search_path"
    # incorrect GIR due to gobject-introspection GitLab issue #189
    ignore = true
    [[object.function]]
    pattern = "choose_icon.*"
    # incorrect GIR due to gobject-introspection GitLab issue #189
    ignore = true
