[options]
work_mode = "sys"
library = "Gdk"
version = "3.0"
min_cfg_version = "3.4"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "GdkPixbuf",
   "Pango",
   "Cairo",
]

[[object]]
name = "Gdk.EventType"
status = "generate"
    [[object.member]]
    name = "2button_press"
    alias = true
    [[object.member]]
    name = "3button_press"
    alias = true
    [[object.member]]
    name = "touchpad_swipe"
    version = "3.18"
    [[object.member]]
    name = "touchpad_pinch"
    version = "3.18"
    [[object.member]]
    name = "event_last"
    alias = true
