[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf-sys = { path = "../gdk-pixbuf-sys" }
gio-sys = { path = "../gio-sys" }
glib-sys = { path = "../glib-sys" }
gobject-sys = { path = "../gobject-sys" }
pango-sys = { path = "../pango-sys" }

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v3_10 = ["v3_8"]
v3_12 = ["v3_10"]
v3_14 = ["v3_12"]
v3_16 = ["v3_14"]
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_22 = ["v3_20"]
v3_6 = []
v3_8 = ["v3_6"]

[lib]
name = "gdk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgdk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk"
name = "gdk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.7.0"
